export const SAVE_TRANSFER_KEY = 'SAVE_TRANSFER';
export const OFFLINE_MODE_KEY = 'OFFLINE_MODE';
export const QUALITY_STREAMING_KEY = 'QUALITY_STREAMING';
export const QUALITY_DOWNLOAD_KEY = 'QUALITY_DOWNLOAD';
export const DOWNLOAD_MOBILE_NETWORK_KEY = 'DOWNLOAD_MOBILE_NETWORK';

export const STORAGE_CHART_KEY = 'STORAGE_CHART';
export const CACHE_FILES_KEY = 'CACHE_FILES';
export const REMOVE_CACHE_KEY = 'REMOVE_CACHE';
export const APP_VERSION_KEY = 'APP_VERSION';
export const LOGOUT_KEY = 'LOGOUT';
export const CLEAR_SEARCH_HISTORY_KEY = 'CLEAR_SEARCH_HISTORY';
export const UPDATE_KEY = 'UPDATE';
