export enum CastMessageType {
    DEVICE_ADDED = 'DEVICE_ADDED',
    DEVICE_CHANGED = 'DEVICE_CHANGED',
    DEVICE_REMOVED = 'DEVICE_REMOVED',
    DEVICE_SELECTED = 'DEVICE_SELECTED',
    DEViCE_UNSELECTED = 'DEViCE_UNSELECTED'
}
